# Generated by Django 4.2.6 on 2023-10-15 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_description', models.CharField(max_length=650)),
                ('product_price', models.FloatField()),
                ('ProductCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.productcategory')),
            ],
        ),
    ]
