# Generated by Django 4.2.6 on 2023-10-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='exp_date',
            field=models.DateField(null=True),
        ),
    ]
