# Generated by Django 4.2.6 on 2023-10-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_rename_productcategory_products_productcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='productCategory',
            new_name='product_category',
        ),
    ]
